// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7608xDVZx-d8KCjYiAsLwlT4p4qHzkW8',
    appId: '1:713512622317:web:9a51862e909616271014e4',
    messagingSenderId: '713512622317',
    projectId: 'textsummarize-d63dd',
    authDomain: 'textsummarize-d63dd.firebaseapp.com',
    storageBucket: 'textsummarize-d63dd.firebasestorage.app',
    measurementId: 'G-G38N5M6E11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE3qUN1FDLZXOBy1H2ygVZIHbcIvCXzx0',
    appId: '1:713512622317:android:3913b903e2f280d81014e4',
    messagingSenderId: '713512622317',
    projectId: 'textsummarize-d63dd',
    storageBucket: 'textsummarize-d63dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzt6imG-NufVvopjN7gGQdZbzT_YXGewY',
    appId: '1:713512622317:ios:18fc1dde7ca484551014e4',
    messagingSenderId: '713512622317',
    projectId: 'textsummarize-d63dd',
    storageBucket: 'textsummarize-d63dd.firebasestorage.app',
    iosBundleId: 'com.example.textsummarize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzt6imG-NufVvopjN7gGQdZbzT_YXGewY',
    appId: '1:713512622317:ios:18fc1dde7ca484551014e4',
    messagingSenderId: '713512622317',
    projectId: 'textsummarize-d63dd',
    storageBucket: 'textsummarize-d63dd.firebasestorage.app',
    iosBundleId: 'com.example.textsummarize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7608xDVZx-d8KCjYiAsLwlT4p4qHzkW8',
    appId: '1:713512622317:web:b9b639d09cc972b91014e4',
    messagingSenderId: '713512622317',
    projectId: 'textsummarize-d63dd',
    authDomain: 'textsummarize-d63dd.firebaseapp.com',
    storageBucket: 'textsummarize-d63dd.firebasestorage.app',
    measurementId: 'G-CVGYVD7393',
  );
}
